language: python

sudo: false

python:
  - "2.7"

install:
  - pip install -r requirements.txt
  - pip install -e .
  - pip install coveralls

script: 
  py.test -v --cov=dknorway .

after_success:
  coveralls

